config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'startes#top'
	resources :'negishes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/negishi.rb
class Negishi < ApplicationRecord
	attachment :image
	validates :title, presence: true
	validates :body, presence: true,  length: { maximum: 200 }
end

app/models/start.rb
class Start < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :start
  validates :name, presence: true,  length: { in: 2..20 }
  # validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 	def after_sign_in_path_for(resource)
		flash[:in]="Signed in successfully."
		root_path
	end

	def after_sign_out_path_for(resource)
		flash[:out]="Signed out successfully."
		root_path
	end

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/negishes_controller.rb
class NegishesController < ApplicationController
  def new
    @negishi=Negishi.new
  end

  def index
    @negishes=Negishi.all
  end

  def edit
    @negishi=Negishi.find(params[:id])
  end

  def show
    @negishi=Negishi.find(params[:id])
  end

  def create
    negishi=Negishi.new(negishi_params)
    negishi.save
    redirect_to negishes_path
  end

  def destroy
    @negishi=Negishi.find(params[:id])
    # negishi=Negishi.new(negishi_params)
    @negishi.destroy
    redirect_to negishes_path
  end

  def update
    @negishi=Negishi.find(params[:id])
    # negishi=Negishi.new(negishi_params)
    @negishi.update(negishi_params)
    redirect_to negish_path(@negishi.id)
  end

  private
  def negishi_params
    params.require(:negishi).permit(:title, :body, :image)
  end
end

app/controllers/startes_controller.rb
class StartesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/negishes_helper.rb
module NegishesHelper
end

app/helpers/startes_helper.rb
module StartesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers4</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/negishes/edit.html.erb
<h1>編集画面</h1>
<%=form_for @negishi, url:negish_path(@negishi.id) do |k| %>

<table class="table table-striped">

	<tr><th>Title</th></tr>
	<tr><td><%=k.text_field :title%></td></tr>

	<tr><th>Body</th></tr>
	<tr><td><%=k.text_area :body%></td></tr>

	<tr><th>Image</th></tr>
	<tr><td><%=k.attachment_field :image%></td></tr>
	
	<tr><td><%=k.submit '保存',class:"btn btn-primary btn-sm active"%></td></tr>

	<tr><td><%=link_to '投稿一覧', negishes_path,class:"btn btn-primary btn-sm active"%></td></tr>

</table>

<% end %>

<!-- <table class="table table-striped">
	<tr><th></th></tr>
	<tr><td></td></tr>

	<tr><th></th></tr>
	<tr><td></td></tr>

	<tr><th></th></tr>
	<tr><td></td></tr>

	<tr><td></td></tr>
</table> -->

app/views/negishes/index.html.erb
<h1>投稿一覧</h1>

<% @negishes.each do |c| %>

<table class="table table-striped">
	<thead>
		<tr><th>Title</th><th>Body</th><th>Image</th></tr>
	</thead>
	<tbody>
		<tr><td><%=link_to c.title, negish_path(c.id) %></td><td><%=link_to c.body, negish_path(c.id)%></td><td><%=attachment_image_tag c, :image, format: 'jpeg', size:'100x100', class:"profile_image", fallback:"no-image.jpg", size:'100x100' %></td><td><%=link_to '削除', negish_path(c.id), method: :delete, "data-confirm" => "本当に削除しますか？",class:"btn btn-primary btn-sm active" %></td></tr>
	</tbody>
	
	
</table>

<% end %>

<%=link_to 'Topへ', root_path,class:"btn btn-warning btn-lg active" %>

app/views/negishes/new.html.erb
<h1>新規投稿</h1>

<%=form_for @negishi, url:'/negishes' do |f| %>

<table class="table table-striped">

	<tr><th>Title</th></tr>
	<tr><td><%=f.text_field :title%></td></tr>

	<tr><th>Body</th></tr>
	<tr><td><%=f.text_area :body%></td></tr>

	<tr><th>Image</th></tr>
	<tr><td><%= f.attachment_field :image,class:"btn btn-warning btn-sm active"%><br></td></tr>

	<tr><td><%= f.submit "投稿",class:"btn btn-warning btn-lg active" %></td></tr>

</table>

<% end %>

app/views/negishes/show.html.erb
<h1>詳細画面</h1>
<table class="table table-striped">

	<tr><th>Title</th></tr>
	<tr><td><%=@negishi.title%></td></tr>

	<tr><th>Body</th></tr>
	<tr><td><%=@negishi.body%></td></tr>

	<tr><th>Image</th></tr>
	<tr><td><%=attachment_image_tag @negishi, :image, format: 'jpeg', size:'100x100', class:"profile_image", fallback:"no-image.jpg", size:'100x100'%></td></tr>

	<tr><td><%=link_to '', edit_negish_path(@negishi),class: "btn btn-success btn-sm active glyphicon glyphicon-wrench" %></td></tr>

	<tr><td><%=link_to '投稿一覧', negishes_path,class:"btn btn-success btn-sm active"%></td></tr>
	
	<tr><td><%=link_to '削除', negish_path(@negishi), method: :delete, "data-confirm" => "本当に削除しますか？",class:"btn btn-success btn-sm active" %></td></tr>

</table>

<!-- ,class:"btn btn-success btn-sm active" -->

app/views/startes/top.html.erb
<% if flash[:out] %>
<div class="flash">
	<%= flash[:out] %>
</div>

<% elsif flash[:in] %>
<div class="flash">
	<%= flash[:in] %>
</div>

<% end %>

<h1>Art</h1>

<table class="table table-striped">

	<tr><td><h3>自分の絵を投稿して人からの評価をお貰えるサイトです</h3></td></tr>

	<% if user_signed_in? %>
	<tr><td><%=link_to 'まずは投稿',new_negish_path,class:"btn btn-info btn-lg active"  %></td></tr>

	<tr><td><%=link_to 'ログアウト',destroy_user_session_path, method: :delete,class:"btn btn-info btn-lg active" %></td></tr>

	<%else%>

	<tr><td><%=link_to 'ログイン' ,new_user_session_path,class:"btn btn-info btn-lg active"%></td></tr>

	<tr><td><%= link_to '新規会員' ,new_user_registration_path,class:"btn btn-info btn-lg active" %></td></tr>
	<%end%>

</table>